export interface Course {
  id: string;
  title: string;
  description: string;
  thumbnail_url?: string;
  created_at: string;
  updated_at: string;
  created_by: string;
  is_premium: boolean;
  categories: string[];
  content_type?: string;
  content_url?: string;
  original_filename?: string;
  is_external_url?: boolean;
  duration?: string;
  content?: string;
  instructor_id?: string;
  status?: 'draft' | 'published' | 'archived';
  price?: number;
  rating?: number;
  total_students?: number;
  total_lessons?: number;
  total_hours?: number;
  requirements?: string[];
  learning_outcomes?: string[];
  level?: 'beginner' | 'intermediate' | 'advanced';
  language?: string;
  last_updated?: string;
  slug?: string;
  preview_url?: string;
  certificate_available?: boolean;
  discount_price?: number | null;
  discount_expiry?: string | null;
  tags?: string[];
  featured?: boolean;
  average_rating?: number;
  total_reviews?: number;
  welcome_message?: string;
  completion_message?: string;
  welcome_video_url?: string;
  welcome_video_thumbnail_url?: string;
  welcome_video_duration?: number;
  welcome_video_title?: string;
  welcome_video_description?: string;
  welcome_video_platform?: 'youtube' | 'vimeo' | 'wistia' | 'custom';
  welcome_video_id?: string;
  welcome_video_embed_code?: string;
  welcome_video_autoplay?: boolean;
  welcome_video_muted?: boolean;
  welcome_video_loop?: boolean;
  welcome_video_controls?: boolean;
  welcome_video_playsinline?: boolean;
  welcome_video_preload?: 'auto' | 'metadata' | 'none';
  welcome_video_aspect_ratio?: '16:9' | '4:3' | '1:1';
  welcome_video_poster_url?: string;
  welcome_video_start_time?: number;
  welcome_video_end_time?: number;
  welcome_video_cc_language?: string;
  welcome_video_cc_url?: string;
  welcome_video_transcript_url?: string;
  welcome_video_chapters_url?: string;
  welcome_video_metadata?: Record<string, any>;
}

export interface UserProfile {
  id: string;
  user_type: 'student' | 'instructor' | 'admin';
  email: string;
  full_name?: string;
  avatar_url?: string;
  created_at: string;
  updated_at: string;
}
