services:
  - type: web
    name: business-analysis-academy
    env: docker
    region: london  # Choose the closest region to your users
    build:
      dockerfile: Dockerfile
    plan: free  # Or 'starter' if you need more resources
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_SUPABASE_URL
        fromService:
          name: business-analysis-academy
          type: web
          property: env.NEXT_PUBLIC_SUPABASE_URL
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        fromService:
          name: business-analysis-academy
          type: web
          property: env.NEXT_PUBLIC_SUPABASE_ANON_KEY
    healthCheckPath: /
    healthCheckTimeout: 60s
    buildCommand: "./render-build.sh"
    startCommand: "npm start"
