services:
  - type: web
    name: bright-lambs
    env: static
    rootDirectory: .
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    envVars:
      - key: NODE_ENV
        value: production
