CREATE TABLE visits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  path text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  anonymised_ip text,
  user_agent text
);

-- Enable Row Level Security
ALTER TABLE public.visits ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anyone to insert a new visit
CREATE POLICY "Allow public insert for visits"
ON public.visits
FOR INSERT
WITH CHECK (true);
